services:
  logistics-service:
    build:
      context: .
      dockerfile: src/main/docker/Dockerfile.jvm
    environment:
      - QUARKUS_DATASOURCE_JDBC_URL=jdbc:postgresql://logistics-db:5432/logistics
      - QUARKUS_HIBERNATE_ORM_DATABASE_GENERATION=update
    ports:
      - "8080:8080"
    depends_on:
      logistics-db:
        condition: service_healthy
    networks:
      - logistics-nw

  logistics-db:
    image: postgres:17
    environment:
      - POSTGRES_USER=logistics
      - POSTGRES_PASSWORD=log101
      - POSTGRES_DB=logistics
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U logistics" ]
      interval: 5s
      timeout: 5s
      retries: 10
    ports:
      - "5432:5432"
    networks:
      - logistics-nw
    volumes:
      - logistics-data:/var/lib/postgresql/data

networks:
  logistics-nw:

volumes:
  logistics-data:
    driver: local