create table products
(
    id          bigint generated by default as identity primary key,
    uuid        varchar(255) unique,
    name        varchar(255) unique,
    grossweight numeric(38, 2),
    height      numeric(38, 2),
    length      numeric(38, 2),
    netweight   numeric(38, 2),
    width       numeric(38, 2)
);

create table storage_units
(
    id             bigint generated by default as identity primary key,
    uuid           varchar(255) unique,
    height         numeric(38, 2),
    length         numeric(38, 2),
    maxunits       integer,
    volumeoccupied numeric(38, 2),
    weightcapacity numeric(38, 2),
    weightoccupied numeric(38, 2),
    width          numeric(38, 2),
    storagestatus  varchar(255),
    storagetype    varchar(255)
);
create index idx_storage_type on storage_units (storagetype);
create index idx_storage_status on storage_units (storagestatus);

create table stocks
(
    id              bigint generated by default as identity primary key,
    barcode         varchar(255) unique,
    expirationdate  date,
    product_id      bigint
        constraint fk_product_id
            references products,
    storage_unit_id bigint
        constraint fk_storage_unit_id
            references storage_units
);

create table transfers
(
    id                     bigint generated by default as identity primary key,
    uuid                   varchar(255) unique,
    source_storage_unit_id bigint not null
        constraint fk_source_storage_unit_id
            references storage_units,
    target_storage_unit_id bigint not null
        constraint fk_target_storage_unit_id
            references storage_units
);

create table transfer_stocks
(
    stock_id    bigint not null
        constraint fk_stock_id
            references stocks,
    transfer_id bigint not null
        constraint fk_transfer_id
            references transfers,
    primary key (stock_id, transfer_id)
);